export class Tags {
    static OCORRENCIA_BOLETOS_CPF_CNPJ_FORA_DA_BASE: 100;
    static OCORRENCIA_BOLETOS_SEM_INTERAÇÃO_DO_CLIENTE: 101;
    static OCORRENCIA_BOLETOS_CPF_CNPJ_INVALIDO: 102;
    static OCORRENCIA_BOLETOS_OPCAO_INVALIDA: 103;
    static OCORRENCIA_BOLETOS_SOLICITAÇAO_FINALIZADA: 104;
    static OCORRENCIA_BOLETOS_OPÇÃO_DE_BOLETO_INVALIDO: 105;
} 
