export class Tags {
    static readonly OCORRENCIA_BOLETOS_CPF_CNPJ_FORA_DA_BASE = 230;
    static readonly OCORRENCIA_BOLETOS_SEM_INTERAÇÃO_DO_CLIENTE = 231;
    static readonly OCORRENCIA_BOLETOS_CPF_CNPJ_INVALIDO = 232;
    static readonly OCORRENCIA_BOLETOS_OPCAO_INVALIDA = 233;
    static readonly OCORRENCIA_BOLETOS_SOLICITAÇAO_FINALIZADA = 234;
    static readonly OCORRENCIA_BOLETOS_OPÇÃO_DE_BOLETO_INVALIDO = 235;
} 
